[build]
builder = "NIXPACKS"
commands = ['build.sh']


[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"asia-southeast1-eqsg3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[start]
gunicorn --chdir backend app:app      