CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  climber_id INTEGER NOT NULL,
  wall_id INTEGER NOT NULL,
  grade TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 1,
  notes TEXT,
  date_recorded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (climber_id) REFERENCES climbers (id),
  FOREIGN KEY (wall_id) REFERENCES walls (id)
)