CREATE TABLE IF NOT EXISTS climbers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  nickname VARCHAR(255),
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)