name: Build and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 22.18.0

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
        env:
          CI: false

      - name: Copy frontend build to backend
        run: |
          mkdir -p backend/build
          cp -r frontend/build/* backend/build/

      - uses: actions/upload-artifact@v4
        name: Upload backend build artifact
        with:
          name: backend-build
          path: backend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/download-artifact@v4
        name: Download backend build artifact
        with:
          name: backend-build
          path: backend/build

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
        working-directory: backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}