# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build React App
        working-directory: frontend
        run: npm run build

      - name: Copy Build Artifacts
        working-directory: frontend
        run: |
          mkdir -p ../backend/build
          cp -r build/* ../backend/build